### ISSUE TITLE
Wandering the meaning

### ISSUE THREAD

**Issue by huhanwj** [Zhmjharmgal/Zhmjharmgal#1]
I don't know Latin, but I really wander the meaning of your self introduction.
Can you translate that to me?

**Comment by Zhmjharmgal** [comment]
Mainly about the fact that I am a jingluo and a heavy PC game player, that I always get obsessed with the game materials.

**Comment by huhanwj** [comment]
> Mainly about the fact that I am a jingluo and a heavy PC game player, that I always get obsessed with the game materials.

however, it seems that you do not own as Rome games like Total War: Rome Remastered or Imperator: Rome or Crusader Kings II/III
how can you tell you are obsessed with the game materials?

**Comment by Zhmjharmgal** [comment]
![image](https://user-images.githubusercontent.com/48463006/116810853-a05ff300-ab78-11eb-846b-05d961049f6c.png)
guess what does this phrase mean XD

**Comment by huhanwj** [comment]
> ![image](https://user-images.githubusercontent.com/48463006/116810853-a05ff300-ab78-11eb-846b-05d961049f6c.png)
> guess what does this phrase mean XD

well this is not that Rome
